version: '3'
services:
  node:
    image: 'node:latest'
    working_dir: '/home/node/app'
    environment:
      - NODE_ENV=development
    volumes:
      - ./packages/mock-server:/home/node/app
    command: 'bash -c "npm install && npm run start"'
    ports:
      - 3000:3000

  localstack:
    image: 'localstack/localstack'
    ports:
      - 4566-4580:4566-4580
      - 8080:8080
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - SERVICES=lambda,stepfunctions,cloudwatch,s3,dynamodb
      - DEBUG=1
      - AWS_ACCESS_KEY=foobar
      - AWS_SECRET_ACCESS_KEY=foobar
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_DOCKER_NETWORK=nlp-slack_default
      - NODE_ENV=development
